version: 0.2

phases:
  install:
    commands:
      - n 20.10.0
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      #list all files
      - ls -la
      #test2
      - echo Build phase...
      - echo enviroment variable
      - echo $ENV_VAR
      - mkdir -p build
      - cp -R * build
artifacts:
  files:
    - build/**
  discard-paths: no